name: CI/CD Workflow  

on:
  push:
    branches: 
      - main

jobs:
  create-docker-image:
    name: Create Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create, tag Docker image
        run: docker buildx build --platform linux/amd64 -t hello-world .
      
      - name: Run Docker image
        env:
          TEST_PARAM: ${{secrets.TEST_PARAM}}
        run: docker run -e TEST_PARAM=$TEST_PARAM hello-world
        
      
      - name: Print TEST_PARAM
        run: echo ${{secrets.TEST_PARAM}}