name: EXPLORE DEPLOY

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: echo "Compiling"
  

  RunTests:
    name: Run Tests
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Running Tests"

  DeployQA:
    name: Deploy to QA
    if: github.event.ref == 'refs/heads/main'
    needs: RunTests
    runs-on: ubuntu-latest
    environment: 
      name: QA
      url: https://qa.example.com
    steps:
      - name: Deploy
        run: echo "Deploying to QA"

  DeployProd:
    name: Deploy to Production
    if: github.event_name == 'push'
    needs: DeployQA
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://example.com
    steps:
      - name: Deploy
        run: echo "Deploying to Production"
      