name: EXPLORE DEPLOY QA

on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: echo "Compiling"
  

  RunTests:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Running Tests"

  DeployQA:
    name: Deploy to QA
    if: github.event.ref == 'refs/heads/qa'
    needs: RunTests
    runs-on: ubuntu-latest
    environment: 
      name: QA
      url: https://qa.example.com
    steps:
      - name: Deploy
        run: echo "Deploying to QA"
      