name: SHOPSTAR DEPLOY

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: echo "Compiling"

  DeployProd:
    name: Deploy to Production
    needs: DeployQA
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://example.com
    steps:
      - name: Deploy
        run: echo "Deploying to Production"
      
